#!/bin/bash
#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Test with full DWARF debugging information.
# Check full signatures of methods.
${RUN} "$@" -Xcompiler-option --generate-debug-info \
            -Xcompiler-option --no-generate-mini-debug-info \
            --args --full-signatures

# Clear the cache for the second run.
rm -rf $DEX_LOCATION/dalvik-cache/

# Test with minimal compressed debugging information.
# Check only method names (parameters are omitted to save space).
${RUN} "$@" -Xcompiler-option --no-generate-debug-info \
            -Xcompiler-option --generate-mini-debug-info
