/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by buildx86opcodes.py.  It's probably best not
// to modify it manually.

#include "x86_opcodes.h"

namespace art {


X86Instruction x86_a2_one_byte[] = {
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // add
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // add
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_v, 0}},  // add
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // add
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // add
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // add
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // adc
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // adc
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_v, 0}},  // adc
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // adc
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // adc
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // adc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // and
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // and
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_v, 0}},  // and
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // and
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // and
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // and
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // daa
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // xor
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // xor
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_v, 0}},  // xor
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // xor
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // xor
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // xor
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // aaa
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // inc
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {0, 0, 0}},  // pushad
  {kX86Instruction, {0, 0, 0}},  // popad
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_M|kX86Op_a, 0}},  // bound
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_d, 0}},  // arpl
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jo
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jno
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jb/nae/c
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jnb/ae/nc
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jz/e
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jnz/ne
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jbe/na
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jnbe/a
  {1, {0, 0, 0}},  // group 1
  {1, {0, 0, 0}},  // group 1
  {1, {0, 0, 0}},  // group 1
  {1, {0, 0, 0}},  // group 1
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // test
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // test
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // xchg
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, 0, 0}},  // xchg
  {kX86Instruction, {kX86OpReg, kX86Op_O|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_O|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86Op_O|kX86Op_b, kX86OpReg, 0}},  // mov
  {kX86Instruction, {kX86Op_O|kX86Op_v, kX86OpReg, 0}},  // mov
  {kX86Instruction, {kX86Op_Y|kX86Op_b, kX86Op_X|kX86Op_b, 0}},  // movs
  {kX86Instruction, {kX86Op_Y|kX86Op_v, kX86Op_X|kX86Op_v, 0}},  // movs
  {kX86Instruction, {kX86Op_Y|kX86Op_b, kX86Op_X|kX86Op_b, 0}},  // cmps
  {kX86Instruction, {kX86Op_X|kX86Op_v, kX86Op_Y|kX86Op_v, 0}},  // cmps
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // mov
  {2, {0, 0, 0}},  // group 2
  {2, {0, 0, 0}},  // group 2
  {kX86Instruction, {kX86Op_I|kX86Op_w, 0, 0}},  // ret
  {kX86Instruction, {0, 0, 0}},  // ret
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_M|kX86Op_p, 0}},  // les
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_M|kX86Op_p, 0}},  // lds
  {11, {0, 0, 0}},  // group 11
  {11, {0, 0, 0}},  // group 11
  {2, {0, 0, 0}},  // group 2
  {2, {0, 0, 0}},  // group 2
  {2, {0, 0, 0}},  // group 2
  {2, {0, 0, 0}},  // group 2
  {kX86Instruction, {kX86Op_I|kX86Op_b, 0, 0}},  // aam
  {kX86Instruction, {kX86Op_I|kX86Op_b, 0, 0}},  // aad
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // xlat
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // loopne
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // loope
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // loop
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jcxz
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // in
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // in
  {kX86Instruction, {kX86Op_I|kX86Op_b, kX86OpReg, 0}},  // out
  {kX86Instruction, {kX86Op_I|kX86Op_b, kX86OpReg, 0}},  // out
  {kX86Instruction, {0, 0, 0}},  // lock
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // repne
  {kX86Instruction, {0, 0, 0}},  // rep
  {kX86Instruction, {0, 0, 0}},  // hlt
  {kX86Instruction, {0, 0, 0}},  // cmc
  {3, {0, 0, 0}},  // group 3
  {3, {0, 0, 0}},  // group 3
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // or
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // or
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_b, 0}},  // or
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // or
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // or
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_z, 0}},  // or
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // sbb
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // sbb
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_b, 0}},  // sbb
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // sbb
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // sbb
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_z, 0}},  // sbb
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // sub
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // sub
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_b, 0}},  // sub
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // sub
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // sub
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_z, 0}},  // sub
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // das
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // cmp
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // cmp
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_b, 0}},  // cmp
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmp
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // cmp
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_z, 0}},  // cmp
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // aas
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // dec
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {kX86Op_I|kX86Op_z, 0, 0}},  // push
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z}},  // imul
  {kX86Instruction, {kX86Op_I|kX86Op_b, 0, 0}},  // push
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b}},  // imul
  {kX86Instruction, {kX86Op_Y|kX86Op_b, kX86OpReg, 0}},  // ins
  {kX86Instruction, {kX86Op_Y|kX86Op_z, kX86OpReg, 0}},  // ins
  {kX86Instruction, {kX86OpReg, kX86Op_X|kX86Op_b, 0}},  // outs
  {kX86Instruction, {kX86OpReg, kX86Op_X|kX86Op_z, 0}},  // outs
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jo
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jno
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jb/cnae
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jae/nb/nc
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // je/z
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jne/nz
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jbe/na
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // ja/nbe
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86Op_G|kX86Op_b, kX86Op_E|kX86Op_b, 0}},  // mov
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86Op_E|kX86Op_w, kX86Op_S|kX86Op_w, 0}},  // mov
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_M, 0}},  // lea
  {kX86Instruction, {kX86Op_S|kX86Op_w, kX86Op_E|kX86Op_w, 0}},  // mov
  {1, {0, 0, 0}},  // group 1
  {kX86Instruction, {0, 0, 0}},  // cbw/cwde/cdqe
  {kX86Instruction, {0, 0, 0}},  // cwd/cdq/cqo
  {kX86Instruction, {kX86Op_A|kX86Op_p, 0, 0}},  // call
  {kX86Instruction, {0, 0, 0}},  // fwait
  {kX86Instruction, {kX86Op_F|kX86Op_v, 0, 0}},  // pushf/d/q
  {kX86Instruction, {kX86Op_F|kX86Op_v, 0, 0}},  // popf/d/q
  {kX86Instruction, {0, 0, 0}},  // sahf
  {kX86Instruction, {0, 0, 0}},  // lahf
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_b, 0}},  // test
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_z, 0}},  // test
  {kX86Instruction, {kX86Op_Y|kX86Op_b, kX86OpReg, 0}},  // stos/b
  {kX86Instruction, {kX86Op_Y|kX86Op_v, kX86OpReg, 0}},  // stos/w/d/q
  {kX86Instruction, {kX86OpReg, kX86Op_X|kX86Op_b, 0}},  // lods/b
  {kX86Instruction, {kX86OpReg, kX86Op_X|kX86Op_v, 0}},  // lods/w/d/q
  {kX86Instruction, {kX86OpReg, kX86Op_Y|kX86Op_b, 0}},  // scas/b
  {kX86Instruction, {kX86OpReg, kX86Op_Y|kX86Op_v, 0}},  // scas/w/d/q
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86OpReg, kX86Op_I|kX86Op_v, 0}},  // mov
  {kX86Instruction, {kX86Op_I|kX86Op_w, kX86Op_I|kX86Op_b, 0}},  // enter
  {kX86Instruction, {0, 0, 0}},  // leave
  {kX86Instruction, {kX86Op_I|kX86Op_w, 0, 0}},  // retf
  {kX86Instruction, {0, 0, 0}},  // retf
  {kX86Instruction, {0, 0, 0}},  // int3
  {kX86Instruction, {kX86Op_I|kX86Op_b, 0, 0}},  // int
  {kX86Instruction, {0, 0, 0}},  // into
  {kX86Instruction, {0, 0, 0}},  // iret/d/q
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {0, 0, 0}},  // esc
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // call
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jmp
  {kX86Instruction, {kX86Op_A|kX86Op_p, 0, 0}},  // jmp
  {kX86Instruction, {kX86Op_J|kX86Op_b, 0, 0}},  // jmp
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // in
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // in
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // out
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // out
  {kX86Instruction, {0, 0, 0}},  // clc
  {kX86Instruction, {0, 0, 0}},  // stc
  {kX86Instruction, {0, 0, 0}},  // cli
  {kX86Instruction, {0, 0, 0}},  // sti
  {kX86Instruction, {0, 0, 0}},  // cld
  {kX86Instruction, {0, 0, 0}},  // std
  {4, {0, 0, 0}},  // group 4
  {5, {0, 0, 0}}  // group 5
};

X86Instruction x86_a3_two_byte[] = {
  {6, {0, 0, 0}},  // group 6
  {7, {0, 0, 0}},  // group 7
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_w, 0}},  // lar
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_w, 0}},  // lsl
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // syscall
  {kX86Instruction, {0, 0, 0}},  // clts
  {kX86Instruction, {0, 0, 0}},  // sysret
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vmovups
  {kX86Instruction, {kX86Op_W|kX86Op_p|kX86Op_s, kX86Op_V|kX86Op_p|kX86Op_s, 0}},  // vmovups
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_M|kX86Op_q, 0}},  // vmovlps
  {kX86Instruction, {kX86Op_M|kX86Op_q, kX86Op_V|kX86Op_p|kX86Op_s, 0}},  // vmovlps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_q, 0}},  // vunpcklps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_q, 0}},  // vunpckhps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_M|kX86Op_q, 0}},  // vmovhps
  {kX86Instruction, {kX86Op_M|kX86Op_q, kX86Op_V|kX86Op_p|kX86Op_s, 0}},  // vmovhps
  {kX86Instruction, {kX86Op_R|kX86Op_d, kX86Op_C|kX86Op_d, 0}},  // mov
  {kX86Instruction, {kX86Op_R|kX86Op_d, kX86Op_D|kX86Op_d, 0}},  // mov
  {kX86Instruction, {kX86Op_C|kX86Op_d, kX86Op_R|kX86Op_d, 0}},  // mov
  {kX86Instruction, {kX86Op_D|kX86Op_d, kX86Op_R|kX86Op_d, 0}},  // mov
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // wrmsr
  {kX86Instruction, {0, 0, 0}},  // rdtsc
  {kX86Instruction, {0, 0, 0}},  // rdmsr
  {kX86Instruction, {0, 0, 0}},  // rdpmc
  {kX86Instruction, {0, 0, 0}},  // sysenter
  {kX86Instruction, {0, 0, 0}},  // sysexit
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // getsec
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovo
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovno
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovb
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnb
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovz
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnz
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovbe
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnbe
  {kX86Instruction, {kX86Op_G|kX86Op_d, kX86Op_V|kX86Op_R|kX86Op_p|kX86Op_s, 0}},  // vmovmskps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vsqrtps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vrsqrtps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vrcpps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vandps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vandnps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vorps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vxorps
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpcklbw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpcklwd
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpckldq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // packsswb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpgtb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpgtw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpgtd
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // packuswb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, kX86Op_I|kX86Op_b}},  // pshufw
  {12, {0, 0, 0}},  // group 12
  {13, {0, 0, 0}},  // group 13
  {14, {0, 0, 0}},  // group 14
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpeqb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpeqw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pcmpeqd
  {kX86Instruction, {0, 0, 0}},  // emms
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jo
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jno
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jb/cnae
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jae/nb/nc
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // je/z
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jne/nz
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jbe/na
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // ja/nbe
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // seto
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setno
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setb/cnae
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setae/nb/nc
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // sete/z
  {kX86Instruction, {0, 0, 0}},  // setne/nEb
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setbe/na
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // seta/nbe
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {0, 0, 0}},  // cpuid
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // bt
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, kX86Op_I|kX86Op_b}},  // shld
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, kX86OpReg}},  // shld
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // cmpxchg
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // cmpxchg
  {kX86Instruction, {kX86Op_G|kX86Op_z, kX86Op_M|kX86Op_p, 0}},  // lss
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // btr
  {kX86Instruction, {kX86Op_G|kX86Op_z, kX86Op_M|kX86Op_p, 0}},  // lfs
  {kX86Instruction, {kX86Op_G|kX86Op_z, kX86Op_M|kX86Op_p, 0}},  // lgs
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_b, 0}},  // movzx
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_w, 0}},  // movzx
  {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_G|kX86Op_b, 0}},  // xadd
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // xadd
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, kX86Op_I|kX86Op_b}},  // vcmpps
  {kX86Instruction, {kX86Op_M|kX86Op_d, kX86Op_G|kX86Op_d, 0}},  // movnti
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_E|kX86Op_w, kX86Op_I|kX86Op_b}},  // pinsrw
  {kX86Instruction, {kX86Op_G|kX86Op_d, kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b}},  // pextrw
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, kX86Op_I|kX86Op_b}},  // vshufps
  {9, {0, 0, 0}},  // group 9
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psrlw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psrld
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psrlq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmullw
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_P|kX86Op_R|kX86Op_d, 0}},  // pmovmskb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pavgb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psraw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psrad
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pavgw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmulhuw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmulhw
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_M|kX86Op_q, kX86Op_P|kX86Op_q, 0}},  // movntq
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psllw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pslld
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psllq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmuludq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmaddwd
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psadbw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_P|kX86Op_R|kX86Op_d, 0}},  // maskmovq
  {kX86Instruction, {0, 0, 0}},  // invd
  {kX86Instruction, {0, 0, 0}},  // wbinvd
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // ud2
  {kX86UndefinedOpcode, {0, 0, 0}},
  {17, {0, 0, 0}},  // group 17
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {16, {0, 0, 0}},  // group 16
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // nop
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vmovaps
  {kX86Instruction, {kX86Op_W|kX86Op_p|kX86Op_s, kX86Op_V|kX86Op_p|kX86Op_s, 0}},  // vmovaps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_Q|kX86Op_d, 0}},  // cvtpi2ps
  {kX86Instruction, {kX86Op_M|kX86Op_d|kX86Op_q, kX86Op_V|kX86Op_p|kX86Op_s, 0}},  // vmovntps
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // cvttps2pi
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // cvtps2pi
  {kX86Instruction, {kX86Op_V|kX86Op_s|kX86Op_s, kX86Op_W|kX86Op_s|kX86Op_s, 0}},  // vucomiss
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vcomiss
  {kX86Instruction, {0, 0, 0}},  // 3byte
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {0, 0, 0}},  // 3byte
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovs
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovns
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovp
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnp
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovl
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnl
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovle
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // cmovnle
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vaddps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vmulps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vcvtps2pd
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vcvtdq2ps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vsubps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vminps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vdivps
  {kX86Instruction, {kX86Op_V|kX86Op_p|kX86Op_s, kX86Op_W|kX86Op_p|kX86Op_s, 0}},  // vmaxps
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpckhbw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpckhwd
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // punpckhdq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // packssdw
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_E|kX86Op_d, 0}},  // movd/q
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // movq
  {kX86Instruction, {kX86Op_E|kX86Op_y, kX86Op_G|kX86Op_y, 0}},  // vmread
  {kX86Instruction, {kX86Op_G|kX86Op_y, kX86Op_E|kX86Op_y, 0}},  // vmwrite
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86UndefinedOpcode, {0, 0, 0}},
  {kX86Instruction, {kX86Op_E|kX86Op_d, kX86Op_P|kX86Op_d, 0}},  // movd/q
  {kX86Instruction, {kX86Op_Q|kX86Op_d, kX86Op_P|kX86Op_q, 0}},  // movq
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // js
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jns
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jp/pe
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jnp/po
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jl/nge
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jnl/ge
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jle/ng
  {kX86Instruction, {kX86Op_J|kX86Op_z, 0, 0}},  // jnle/g
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // sets
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setns
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setp/pe
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setnp/po
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setl/nge
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setl/ge/n
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setle/ng
  {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // setle/g
  {kX86Instruction, {kX86OpReg, 0, 0}},  // push
  {kX86Instruction, {kX86OpReg, 0, 0}},  // pop
  {kX86Instruction, {0, 0, 0}},  // rsm
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // bts
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, kX86Op_I|kX86Op_b}},  // shrd
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, kX86OpReg}},  // shrd
  {15, {0, 0, 0}},  // group 15
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // imul
  {kX86Instruction, {0, 0, 0}},  // jmpe
  {10, {0, 0, 0}},  // group 10
  {8, {0, 0, 0}},  // group 8
  {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_G|kX86Op_v, 0}},  // btc
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // bsf
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_v, 0}},  // bsr
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_b, 0}},  // movsx
  {kX86Instruction, {kX86Op_G|kX86Op_v, kX86Op_E|kX86Op_w, 0}},  // movsx
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86OpReg, kX86OpReg, 0}},  // bswap
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubusb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubusw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pminub
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pand
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddusb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddusw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmaxub
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pandn
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubsb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubsw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pminsw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // por
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddsb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddsw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pmaxsw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // pxor
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubd
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // psubq
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddb
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddw
  {kX86Instruction, {kX86Op_P|kX86Op_q, kX86Op_Q|kX86Op_d, 0}},  // paddd
  {kX86UndefinedOpcode, {0, 0, 0}}
};

X86Group x86_groups[] = {
  {1, 0x80, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // add
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // or
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // adc
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // sbb
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // and
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // sub
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // xor
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}}  // cmp
  }},
  {1, 0x81, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // add
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // or
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // adc
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // sbb
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // and
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // sub
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // xor
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}}  // cmp
  }},
  {1, 0x82, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // add
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // or
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // adc
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // sbb
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // and
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // sub
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // xor
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}}  // cmp
  }},
  {1, 0x83, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // add
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // or
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // adc
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // sbb
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // and
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // sub
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // xor
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}}  // cmp
  }},
  {1, 0x8f, {
    {kX86Instruction, {0, 0, 0}},  // pop
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {2, 0xc0, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}}  // sar
  }},
  {2, 0xc1, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}}  // sar
  }},
  {2, 0xd0, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_1, 0}}  // sar
  }},
  {2, 0xd1, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_1, 0}}  // sar
  }},
  {2, 0xd2, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86OpReg, 0}}  // sar
  }},
  {2, 0xd3, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // rol
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // ror
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // rcl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // rcr
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // shl
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}},  // shr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86OpReg, 0}}  // sar
  }},
  {3, 0xf6, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // test
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // not
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // neg
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // mul
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // imul
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // div
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}}  // idiv
  }},
  {3, 0xf7, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // test
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // not
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // neg
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // mul
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // imul
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // div
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}}  // idiv
  }},
  {4, 0xfe, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // inc
    {kX86Instruction, {kX86Op_E|kX86Op_b, 0, 0}},  // dec
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {5, 0xff, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // inc
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // dec
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // call
    {kX86Instruction, {kX86Op_E|kX86Op_p, 0, 0}},  // call
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // jmp
    {kX86Instruction, {kX86Op_E|kX86Op_p, 0, 0}},  // jmp
    {kX86Instruction, {kX86Op_E|kX86Op_v, 0, 0}},  // push
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {6, 0x0f00, {
    {kX86Instruction, {kX86Op_M|kX86Op_w, kX86Op_R|kX86Op_v, 0}},  // sldt
    {kX86Instruction, {kX86Op_M|kX86Op_w, kX86Op_R|kX86Op_v, 0}},  // str
    {kX86Instruction, {kX86Op_E|kX86Op_w, 0, 0}},  // lldt
    {kX86Instruction, {kX86Op_E|kX86Op_w, 0, 0}},  // ltr
    {kX86Instruction, {kX86Op_E|kX86Op_w, 0, 0}},  // verr
    {kX86Instruction, {kX86Op_E|kX86Op_w, 0, 0}},  // verw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {7, 0x0f01, {
    {kX86Instruction, {kX86Op_M|kX86Op_s, 0, 0}},  // sgdt
    {kX86Instruction, {kX86Op_M|kX86Op_s, 0, 0}},  // sidt
    {kX86Instruction, {kX86Op_M|kX86Op_s, 0, 0}},  // lgdt
    {kX86Instruction, {kX86Op_M|kX86Op_s, 0, 0}},  // lidt
    {kX86Instruction, {kX86Op_M|kX86Op_w, 0, 0}},  // smsw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_w, 0, 0}},  // lmsw
    {kX86Instruction, {kX86Op_M|kX86Op_b, 0, 0}}  // invlpg
  }},
  {8, 0x0fba, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // bt
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // bts
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}},  // btr
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_b, 0}}  // btc
  }},
  {9, 0x0fc7, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_M|kX86Op_q, 0, 0}},  // cmpxchg8b
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {10, 0x0fb9, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {11, 0xc6, {
    {kX86Instruction, {kX86Op_E|kX86Op_b, kX86Op_I|kX86Op_b, 0}},  // mov
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {11, 0xc7, {
    {kX86Instruction, {kX86Op_E|kX86Op_v, kX86Op_I|kX86Op_z, 0}},  // mov
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {12, 0x0f71, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrlw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psraw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psllw
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {12, 0x660f71, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrlw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psraw
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psllw
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {13, 0x0f72, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrld
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrad
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // pslld
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {13, 0x660f72, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrld
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrad
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // pslld
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {14, 0x0f73, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrlq
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_P|kX86Op_R|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psllq
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {14, 0x660f73, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrlq
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psrldq
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}},  // psllq
    {kX86Instruction, {kX86Op_V|kX86Op_R|kX86Op_d|kX86Op_q, kX86Op_I|kX86Op_b, 0}}  // pslldq
  }},
  {15, 0x0fae, {
    {kX86Instruction, {kX86Op_M, 0, 0}},  // fxsave
    {kX86Instruction, {kX86Op_M, 0, 0}},  // fsrstor
    {kX86Instruction, {kX86Op_M|kX86Op_d, 0, 0}},  // ldmxcsr
    {kX86Instruction, {kX86Op_M|kX86Op_d, 0, 0}},  // stmxcsr
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {0, 0, 0}},  // lfence
    {kX86Instruction, {0, 0, 0}},  // mfence
    {kX86Instruction, {0, 0, 0}}  // sfence
  }},
  {16, 0x0f18, {
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86Instruction, {0, 0, 0}},  // nop
    {kX86Instruction, {0, 0, 0}},  // nop
    {kX86Instruction, {0, 0, 0}},  // nop
    {kX86Instruction, {0, 0, 0}}  // nop
  }},
  {17, 0x0f0d, {
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86Instruction, {0, 0, 0}},  // prefetch
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }},
  {0xff, 0, {
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}},
    {kX86UndefinedOpcode, {0, 0, 0}}
  }}
};

}        // namespace art
