#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if echo $@ | grep -q -- "--jvm"; then
  mkdir src || exit 1
  mkdir classes || exit 1
  ./util-src/generate_java.sh ./smali ./src || exit 1
  ${JAVAC} -implicit:none -classpath src-multidex -d classes `find src -name '*.java'` || exit 1
fi

${SMALI} -JXmx512m --experimental --api-level 23 --output classes.dex `find smali -name '*.smali'` || exit 1
zip $TEST_NAME.jar classes.dex || exit 1
